# Subdirectory makefile for Vector enumerator GF(p) version

override VFLAG=-DME # define this when compiling
override XTRAOBJS= scrut.o  # no extra object files (eg lattice.c)
override XTRADEPS= # special dependencies for the extra files
override XTRAGDEPS= # special d
override PROGNAME=me # what to call the final program
override ARITHLIB=  # no extra library declarations 

include ../../Makefile.inc
