# Subdirectory makefile for Vector enumerator rational

override VFLAG=-DQME # define this when compiling
override XTRAOBJS= scrut.o #  extra object files (eg lattice.o)
override XTRADEPS=
override XTRAGDEPS=
override PROGNAME=qme # what to call the final program
override ARITHLIB=  -lgmp  # no extra library declarations 

include ../../Makefile.inc

